version: '3.3'
services:
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./webroot:/var/www/html
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        links:
            - php7
            - db
            - redis
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    php7:
        #image: php:7.4-fpm-alpine
        build: './docker/php7'
        restart: always
        volumes:
            - ./webroot:/var/www/html
        links:
            - db
            - redis
    #php8:
        #image: php:8.0-fpm-alpine
        #restart: always
        #volumes:
            #- ./webroot:/var/www/html
    db:
        image: mysql:5.7
        restart: always
        environment:
            # Password for root access
            MYSQL_ROOT_PASSWORD: ''
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
            - ./data/mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8080:80
    redis:
        image: redis:alpine
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - ./data/redis:/data
        command: redis-server --appendonly yes
